/**
 * Tests for Zcash client — Generated by Zcash Migrate
 *
 * Tests ZebraRPC (zebrad JSON-RPC) and ZkoolWallet (zkool GraphQL) separately.
 * Run: node --test test_zcash_rpc.mjs
 *
 * Requires:
 *   - zebrad running on port 8232 (or ZEBRA_PORT env var)
 *   - zkool_graphql running on port 8000 (or ZKOOL_PORT env var)
 */
import { describe, it, before } from "node:test";
import assert from "node:assert/strict";
import { ZebraRPC, ZkoolWallet, ZcashClient } from "./zcash_rpc.cjs";

const zebra = new ZebraRPC({
  host: process.env.ZEBRA_HOST || "127.0.0.1",
  port: parseInt(process.env.ZEBRA_PORT || "8232"),
  user: process.env.ZEBRA_USER || "",
  password: process.env.ZEBRA_PASSWORD || "",
});

const zkool = new ZkoolWallet({
  host: process.env.ZKOOL_HOST || "127.0.0.1",
  port: parseInt(process.env.ZKOOL_PORT || "8000"),
});

// ─── ZebraRPC tests (chain data via zebrad) ─────────────────────────

describe("ZebraRPC (zebrad chain data)", () => {
  it("getblockchaininfo", async () => {
    const info = await zebra.getblockchaininfo();
    assert.ok(info.chain);
    assert.ok(typeof info.blocks === "number");
  });

  it("getbestblockhash", async () => {
    const hash = await zebra.getbestblockhash();
    assert.ok(typeof hash === "string");
    assert.equal(hash.length, 64); // 32 bytes hex
  });

  it("getblock by hash", async () => {
    const hash = await zebra.getbestblockhash();
    const block = await zebra.getblock(hash, 1);
    assert.ok("height" in block);
    assert.ok("tx" in block);
  });

  it("getblock by height", async () => {
    const block = await zebra.getblock(1, 1);
    assert.equal(block.height, 1);
  });

  it("z_validateaddress (valid transparent)", async () => {
    const result = await zebra.z_validateaddress("t1Hsc1LR8yKnbbe3twRp88p6vFfC87hPDFp");
    assert.ok("isvalid" in result);
  });

  it("z_validateaddress (invalid)", async () => {
    const result = await zebra.z_validateaddress("invalid_address_xyz");
    assert.equal(result.isvalid, false);
  });

  it("getaddressbalance", async () => {
    const result = await zebra.getaddressbalance(["t1Hsc1LR8yKnbbe3twRp88p6vFfC87hPDFp"]);
    assert.ok("balance" in result);
  });

  it("z_listunifiedreceivers rejects bad input", async () => {
    await assert.rejects(
      () => zebra.z_listunifiedreceivers("not_a_unified_address"),
      /error/i,
    );
  });
});

// ─── ZkoolWallet tests (wallet ops via zkool_graphql) ───────────────

describe("ZkoolWallet (zkool GraphQL)", { skip: !process.env.ZKOOL_TEST_ACCOUNT }, () => {
  const accountId = parseInt(process.env.ZKOOL_ACCOUNT_ID || "1");

  it("sync account", async () => {
    const result = await zkool.sync(accountId);
    assert.ok(result !== undefined);
  });

  it("getBalance returns pool breakdown", async () => {
    const result = await zkool.getBalance(accountId);
    const bal = result.balanceByAccount;
    assert.ok("transparent" in bal);
    assert.ok("sapling" in bal);
    assert.ok("orchard" in bal);
    assert.ok("total" in bal);
  });

  it("getAddresses returns UA", async () => {
    const result = await zkool.getAddresses(accountId, 6);
    const addr = result.addressByAccount;
    assert.ok("ua" in addr); // Unified Address (u1...)
  });

  it("getNotes returns array", async () => {
    const result = await zkool.getNotes(accountId);
    assert.ok("notesByAccount" in result);
  });

  it("getTransactions returns history", async () => {
    const result = await zkool.getTransactions(accountId);
    assert.ok("transactionsByAccount" in result);
  });
});

describe("ZkoolWallet send", { skip: !process.env.ZKOOL_TEST_SEND }, () => {
  it("send with Orchard pool", async () => {
    const accountId = parseInt(process.env.ZKOOL_ACCOUNT_ID || "1");
    const toAddr = process.env.ZKOOL_TEST_RECIPIENT;
    assert.ok(toAddr, "Set ZKOOL_TEST_RECIPIENT env var");
    const result = await zkool.send(
      accountId,
      [{ address: toAddr, amount: 0.0001 }],
      4, // Orchard preferred
    );
    assert.ok(result !== undefined);
  });
});

// ─── ZcashClient unified facade ─────────────────────────────────────

describe("ZcashClient (unified)", () => {
  it("has chain and wallet properties", () => {
    const client = new ZcashClient();
    assert.ok(client.chain instanceof ZebraRPC);
    assert.ok(client.wallet instanceof ZkoolWallet);
  });

  it("chain works through client", async () => {
    const client = new ZcashClient();
    const info = await client.chain.getblockchaininfo();
    assert.ok(info.chain);
  });
});
