/**
 * Zcash Client — Generated by Zcash Migrate
 *
 * Architecture:
 *   - ZebraRPC: connects to zebrad (JSON-RPC, port 8232) for chain data.
 *     zebrad is a Zcash node — it serves blockchain state but has NO wallet.
 *   - ZkoolWallet: connects to zkool_graphql (GraphQL, port 8000) for wallet ops.
 *     zkool handles account creation, syncing, address generation, and the
 *     'pay' mutation which builds Orchard/Halo2 proofs and broadcasts txs.
 *   - ZcashClient: unified facade combining both.
 *
 * Shielded Pools:
 *   - Transparent (pool=1): public, like Bitcoin. Addresses start with t1/t3.
 *   - Sapling (pool=2): zk-SNARK (Groth16). Addresses start with zs...
 *   - Orchard (pool=4): zk-SNARK (Halo2). No trusted setup. Latest pool.
 *     Orchard addresses are embedded in Unified Addresses (u1...).
 *   - Pool bitmask: 1=transparent, 2=sapling, 4=orchard, 6=sapling+orchard, 7=all.
 *
 * Zero dependencies. Works with Node.js 18+ (native fetch).
 */

class ZebraRPC {
  /**
   * JSON-RPC client for zebrad (chain data only, no wallet RPCs).
   * Default port: 8232 (mainnet), 18232 (testnet).
   */
  constructor({ host = "127.0.0.1", port = 8232, user = "", password = "" } = {}) {
    this.url = `http://${host}:${port}`;
    this.auth = user || password ? Buffer.from(`${user}:${password}`).toString("base64") : null;
    this._id = 0;
  }

  async call(method, params = []) {
    this._id++;
    const headers = { "Content-Type": "application/json" };
    if (this.auth) headers["Authorization"] = `Basic ${this.auth}`;
    const res = await fetch(this.url, {
      method: "POST",
      headers,
      body: JSON.stringify({ jsonrpc: "2.0", id: this._id, method, params }),
    });
    const json = await res.json();
    if (json.error) throw new Error(`RPC error: ${JSON.stringify(json.error)}`);
    return json.result;
  }

  // ─── Chain state ──────────────────────────────────────────────────

  /** Get current chain info: network, blocks, best block hash, etc. */
  getblockchaininfo() { return this.call("getblockchaininfo"); }

  /** Get the hash of the best (most recent) block. */
  getbestblockhash() { return this.call("getbestblockhash"); }

  /** Get block data. verbosity: 0=hex, 1=json, 2=json+tx details. */
  getblock(hashOrHeight, verbosity = 1) { return this.call("getblock", [String(hashOrHeight), verbosity]); }

  /** Get raw transaction. verbose=1 returns decoded JSON. */
  getrawtransaction(txid, verbose = 1) { return this.call("getrawtransaction", [txid, verbose]); }

  /** Broadcast a raw transaction hex to the network. */
  sendrawtransaction(hexString) { return this.call("sendrawtransaction", [hexString]); }

  // ─── Transparent address queries (no wallet needed) ───────────────

  /**
   * Get transparent balance for one or more t-addresses.
   * Returns {balance: <zatoshis>}. 1 ZEC = 100_000_000 zatoshis.
   * NOTE: Only transparent funds. For shielded, use ZkoolWallet.getBalance().
   */
  getaddressbalance(addresses) { return this.call("getaddressbalance", [{ addresses }]); }

  /** Get transaction IDs for transparent addresses in block range. */
  getaddresstxids(addresses, start, end) { return this.call("getaddresstxids", [{ addresses, start, end }]); }

  // ─── Address validation and decomposition ─────────────────────────

  /** Validate any Zcash address (transparent, sapling, or unified). */
  z_validateaddress(address) { return this.call("z_validateaddress", [address]); }

  /**
   * Decompose a Unified Address (u1...) into its pool receivers.
   * Returns {orchard, sapling, p2pkh} depending on which pools the UA encodes.
   */
  z_listunifiedreceivers(address) { return this.call("z_listunifiedreceivers", [address]); }
}


class ZkoolWallet {
  /**
   * GraphQL client for zkool_graphql (wallet operations).
   * Handles account creation, syncing, address derivation, and the
   * 'pay' mutation which builds Orchard/Halo2 proofs and broadcasts.
   * Default port: 8000.
   */
  constructor({ host = "127.0.0.1", port = 8000, timeout = 60000 } = {}) {
    this.url = `http://${host}:${port}/graphql`;
    this.timeout = timeout;
  }

  async _query(query, variables = {}) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), this.timeout);
    try {
      const res = await fetch(this.url, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ query, variables }),
        signal: controller.signal,
      });
      const json = await res.json();
      if (json.errors) {
        const msgs = json.errors.map((e) => e.message).join("; ");
        throw new Error(`GraphQL error: ${msgs}`);
      }
      return json.data;
    } finally {
      clearTimeout(timer);
    }
  }

  // ─── Account management ───────────────────────────────────────────

  /**
   * Create a new HD wallet account.
   * @param {string} name - Human-readable account label.
   * @param {string} key - Seed phrase or spending key.
   * @param {number} pools - Bitmask: 1=transparent, 2=sapling, 4=orchard, 7=all.
   * @returns Account ID (int).
   */
  createAccount(name, key, pools = 7) {
    return this._query(
      `mutation CreateAccount($name: String!, $key: String!, $pools: Int!) {
        createAccount(name: $name, key: $key, pools: $pools)
      }`,
      { name, key, pools },
    );
  }

  /**
   * Synchronize account with the blockchain.
   * Downloads and trial-decrypts blocks to find notes belonging to this account.
   * Must be called before getBalance/getNotes.
   */
  sync(accountId) {
    return this._query(
      `mutation Synchronize($idAccount: Int!) {
        synchronize(idAccount: $idAccount)
      }`,
      { accountId },
    );
  }

  // ─── Balance and addresses ────────────────────────────────────────

  /**
   * Get shielded + transparent balance for an account.
   * @returns {transparent, sapling, orchard, total} in ZEC.
   */
  getBalance(accountId) {
    return this._query(
      `query BalanceByAccount($idAccount: Int!) {
        balanceByAccount(idAccount: $idAccount) {
          transparent
          sapling
          orchard
          total
        }
      }`,
      { accountId },
    );
  }

  /**
   * Get addresses for an account.
   * @param {number} pools - Bitmask. Default 6 = sapling+orchard (shielded only).
   *   Use 4 for Orchard-only UA, 7 for all pools.
   * @returns {ua, transparent, sapling, orchard}
   */
  getAddresses(accountId, pools = 6) {
    return this._query(
      `query AddressByAccount($idAccount: Int!, $pools: Int!) {
        addressByAccount(idAccount: $idAccount, pools: $pools) {
          ua
          transparent
          sapling
          orchard
        }
      }`,
      { accountId, pools },
    );
  }

  /** Derive new addresses for an account (rotates diversifier). */
  newAddresses(accountId) {
    return this._query(
      `mutation NewAddresses($idAccount: Int!) {
        newAddresses(idAccount: $idAccount) {
          ua
          transparent
          sapling
          orchard
        }
      }`,
      { accountId },
    );
  }

  // ─── Transactions ─────────────────────────────────────────────────

  /**
   * Send ZEC to one or more recipients.
   * This is the key operation — zkool builds the transaction, generates
   * Orchard (Halo2) or Sapling (Groth16) zk-SNARK proofs, and broadcasts
   * through zebrad. Proof generation is CPU-intensive (~2-5s for Orchard).
   *
   * @param {number} accountId - Source account ID.
   * @param {Array<{address: string, amount: number, memo?: string}>} recipients
   * @param {number} srcPools - Bitmask of source pools. 4=orchard (preferred), 7=any.
   * @returns Transaction ID (txid) string.
   */
  send(accountId, recipients, srcPools = 7) {
    return this._query(
      `mutation Pay($idAccount: Int!, $recipients: [RecipientInput!]!, $srcPools: Int!) {
        pay(idAccount: $idAccount, recipients: $recipients, srcPools: $srcPools)
      }`,
      { accountId, recipients, srcPools },
    );
  }

  /**
   * Get unspent notes (shielded UTXOs) for an account.
   * Notes are encrypted on-chain and only visible to the account holder.
   */
  getNotes(accountId) {
    return this._query(
      `query NotesByAccount($idAccount: Int!) {
        notesByAccount(idAccount: $idAccount) {
          id
          amount
          pool
          spent
        }
      }`,
      { accountId },
    );
  }

  /** Get transaction history for an account. */
  getTransactions(accountId) {
    return this._query(
      `query TransactionsByAccount($idAccount: Int!) {
        transactionsByAccount(idAccount: $idAccount) {
          txid
          amount
          height
          timestamp
          pool
        }
      }`,
      { accountId },
    );
  }
}


class ZcashClient {
  /**
   * Unified Zcash client combining zebrad (chain) and zkool (wallet).
   *
   * @example
   * const client = new ZcashClient();
   * // Chain data via zebrad:
   * const info = await client.chain.getblockchaininfo();
   * // Wallet ops via zkool:
   * await client.wallet.sync(1);
   * const bal = await client.wallet.getBalance(1);
   */
  constructor({ zebraHost, zebraPort, zkoolHost, zkoolPort, rpcUser, rpcPassword } = {}) {
    this.chain = new ZebraRPC({
      host: zebraHost || "127.0.0.1",
      port: zebraPort || 8232,
      user: rpcUser || "",
      password: rpcPassword || "",
    });
    this.wallet = new ZkoolWallet({
      host: zkoolHost || "127.0.0.1",
      port: zkoolPort || 8000,
    });
  }
}

module.exports = { ZebraRPC, ZkoolWallet, ZcashClient };
